apiVersion: v1
kind: Service
metadata:
  name: gmail-service
  namespace: gmail-service
  labels:
    app: gmail-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours (for long-lived sessions)
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: gmail-service

---
apiVersion: v1
kind: Service
metadata:
  name: gmail-redis-service
  namespace: gmail-service
  labels:
    app: gmail-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: gmail-redis
